name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests
        uses: ./.github/actions/unit-tests
        with:
          working-directory: "./"

  build:
    needs: unit_tests
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.version.outputs.short_sha }}
      repo_name: ${{ steps.version.outputs.repo_name }}
    steps:
      - name: Extract Version Info
        uses: ./.github/actions/generate-version

      - name: Build and Push Docker Image
        uses: ./.github/actions/docker-build
        with:
          repo-name: ${{ steps.version.outputs.repo_name }}
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSKEY }}
          image-tag: ${{ steps.version.outputs.short_sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Update Kubernetes Config
        uses: ./.github/actions/update-k8s-config
        with:
          gh-token: ${{ secrets.GH_PAT }}
          config-repo: "ChamberFellas/kustomize-config"
          repo-name: ${{ needs.build.outputs.repo_name }}
          image-tag: ${{ needs.build.outputs.image_tag }}

      - name: Deployment Notification
        uses: username/repository-name@v1
        with:
          message: "Image updated in k8s-config repo. ArgoCD will deploy the new version."
